nombre1 = int(input("donam un nombre\n"))
nombre2 = int(input("donam un altre nombre\n"))
nombre3 = int(input("donam l'ultim nombre\n"))
if nombre1>=nombre2>=nombre3:print(" ",nombre1," ",nombre2," ",nombre3)
elif nombre1>=nombre3>=nombre2:print(" ",nombre1," ",nombre3," ",nombre2)
elif nombre2>=nombre1>=nombre3:print(" ",nombre2," ",nombre1," ",nombre3)
elif nombre2>=nombre3>=nombre1:print(" ",nombre2," ",nombre3," ",nombre1)
elif nombre3>=nombre1>=nombre2:print(" ",nombre3," ",nombre1," ",nombre2)
elif nombre3>=nombre2>=nombre1:print(" ",nombre3," ",nombre2," ",nombre1)
