print ("escriu un numero")
entrada1=input()
num1=int(entrada1)
print ("escriu un altre numero")
entrada2=input()
num2=int(entrada2)
print ("la suma es:",num1+num2)
print ("la resta es:",num1-num2)
print ("la multiplicació es:",num1*num2)
print("la divisió es:",num1/num2)
print("el modul es:",num1%num2)
