preucola = int(input("cuan val el teu refresc de cola?\n"))
colavenuda = int(input("quina quantitat s'ha venut\n"))
print("amb la cola has guanyat:",preucola*colavenuda)
preutaron = int(input("valor del refresc de taronja\n"))
taronvenuda = int(input("quants s'han venut?\n"))
print("amb la taronja has guanyat:",preutaron*taronvenuda)
preullim = int(input("valor del refesc de llimona\n"))
llimvenuda = int(input("quantitat venuda\n"))
print("amb la llimona has guanyat:",preullim*llimvenuda)
print("en total has guanyat:",preucola*colavenuda+preutaron*taronvenuda+preullim*llimvenuda)
